spring.application.name=entradasalidas

spring.datasource.url=jdbc:mysql://localhost:3306/entradas_salidas?createDatabaseIfNotExist=true
spring.datasource.username=hackathon
spring.datasource.password=admin1234#

spring.jpa.hibernate.ddl-auto=update